# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Henry Hugo Theme"
description = "Henry is a gorgeous Hugo theme optimmized for a good reading experience and packed with features"
homepage = "https://kau.sh/blog/henry-hugo-theme/"

tags = [
  "website",
  "starter",
  "responsive",
  "Disqus",
  "blog",
  "Tachyons",
  "Multilingual",
  "Stackbit",
]
features = [
  "clean reading experience",
  "beautiful font & type",
  "customizable & versatile",
  "footnotes",
  "sidenotes",
  "multiple image display combinations",
  "image attribution captions",
  "external url",
  "daring fireball style urls",
  "canonical urls",
  "alternate urls aliases",
  "rss feed clean",
  "seo optimized",
  "posts",
  "shortcodes",
  "related posts",
]

# hugo min version
min_version = "0.84.0"

[languages]
[languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1

# goldmark enables far more useful functionality
[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark.parser.attribute]
block = true
title = true

[permalinks]
blog = "/:section/:slug"
ppt = "/:section/:slug"
s = "/:section/:slug"
log = "/:section/:year/:month"
# would have gone "/:section/:year/:month/:day" but allowing flexibility by controlling slug directly
letter = "/:section/:slug"

[params]
bioUrl = "https://kau.sh"
summary = "Code, Culture, Carts & Carnatic Beats: Welcome to Kaush's World"
enableSearch = true
enablePagination = false
avatar = "/images/kg.jpeg"
sitename = "my site's name"
invisibleSections = ["log"]
# github = "https://github.com/kaushikgopal"
# facebook = "https://www.facebook.com/kaushikgopal"
# twitter = "@kaushikgopal"
# googleAnalytics = ""
# enableRobotsTXT = true

[params.author]
name = "Kaushik Gopal"
email = "blog@kau.sh"
url = "https://kau.sh"
avatar = "/images/kg.jpeg"

# Related posts
[related]
includeNewer = true # show related posts from the future
threshold = 80
[[related.indices]]
name = "title"
weight = 60
toLower = true
[[related.indices]]
name = "tags"
weight = 30

# configure RSS feeds for specific pages
[outputs]
# output format for pages
# https://gohugo.io/templates/output-formats/#output-formats-for-pages
page = ["html"]
home = ["HTML", "RSS", "JSON", "SEARCH"]
# sections = directories e.g. blog, letter, ppt
section = ["HTML", "RSS", "JSON"]
# taxonomies = virtual tags/directories e.g. categories, tags (built-in)
# no rss for these as they're mostly "list" pages
taxonomy = ["html"]
# terms = values of taxonomies e.g. categories/programming
term = ["HTML", "RSS", "JSON"]


# enable .json RSS feeds
[outputFormats]
# output formats
# https://gohugo.io/templates/output-formats/#output-format-definitions


# Required for search
[params.search]
enabled = true
[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

# Required for feeds - RSS & JSON
[outputFormats.RSS]
mediatype = "application/rss"
# change RSS path for default XML feed to /feed.xml (default index.xml)
baseName = "feed"
[outputFormats.JSON]
# change RSS path for JSON feed to /feed.json
baseName = "feed"
